# loc()

The loc() method is label-based, so we have to specify rows and columns based on their index/row\
and column labels. So that means that we have to write the name of the index or the name of the column\
in order to get the data we want.

So our first argument will be the name of the index and our second argument will be the name of the column.

# iloc()

The iloc() method is integer position-based, so we have to specify rows and columns by their integer\
position values (0-based integer position, which means that it always starts with zero).

So the main difference between the loc() and iloc() methods is that, with the loc() method we only need\
the column and the index labels. But with the iloc() method we need to specify the integer position values,\
so we have to locate a data inside a dataframe and then see in which position is the row (or the index), and\
in which position is the column.

In [1]:
import pandas as pd

In [2]:
# reading csv file
df = pd.read_csv('players_20.csv')

In [4]:
# showing the dataframe
df.head(3)

,sofifa_id,player_url,short_name,long_name,age,dob,height_cm,weight_kg,nationality,club,...,lwb,ldm,cdm,rdm,rwb,lb,lcb,cb,rcb,rb
0,158023,https://sofifa.com/player/158023/lionel-messi/...,L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona,...,68+2,66+2,66+2,66+2,68+2,63+2,52+2,52+2,52+2,63+2
1,20801,https://sofifa.com/player/20801/c-ronaldo-dos-...,Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus,...,65+3,61+3,61+3,61+3,65+3,61+3,53+3,53+3,53+3,61+3
2,190871,https://sofifa.com/player/190871/neymar-da-sil...,Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain,...,66+3,61+3,61+3,61+3,66+3,61+3,46+3,46+3,46+3,61+3

In [5]:
# And now we can see this dataframe contains information about soccer players: like the age,
# the height, the weight, nationality and so on

# Now that we have the df, the first thing I'm going to do is to set 'short_name' to the index

# short_name is a categorical variable that contains the names of these soccer players. And if we
# set this to the index, now instead of 0, 1, 2, 3, ... in the index, we're going to get the names
# of the players there. So we can identify the rows easily.

In [7]:
# setting index
df.set_index('short_name', inplace=True)

In [8]:
# showing the dataframe
df

,sofifa_id,player_url,long_name,age,dob,height_cm,weight_kg,nationality,club,overall,...,lwb,ldm,cdm,rdm,rwb,lb,lcb,cb,rcb,rb
short_name,,,,,,,,,,,,,,,,,,,,,
L. Messi,158023,https://sofifa.com/player/158023/lionel-messi/...,Lionel Andrés Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona,94,...,68+2,66+2,66+2,66+2,68+2,63+2,52+2,52+2,52+2,63+2
Cristiano Ronaldo,20801,https://sofifa.com/player/20801/c-ronaldo-dos-...,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus,93,...,65+3,61+3,61+3,61+3,65+3,61+3,53+3,53+3,53+3,61+3
Neymar Jr,190871,https://sofifa.com/player/190871/neymar-da-sil...,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain,92,...,66+3,61+3,61+3,61+3,66+3,61+3,46+3,46+3,46+3,61+3
J. Oblak,200389,https://sofifa.com/player/200389/jan-oblak/20/...,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid,91,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
E. Hazard,183277,https://sofifa.com/player/183277/eden-hazard/2...,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid,91,...,66+3,63+3,63+3,63+3,66+3,61+3,49+3,49+3,49+3,61+3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Shao Shuai,245006,https://sofifa.com/player/245006/shuai-shao/20...,邵帅,22,1997-03-10,186,79,China PR,Beijing Renhe FC,48,...,43+2,42+2,42+2,42+2,43+2,45+2,46+2,46+2,46+2,45+2
Xiao Mingjie,250995,https://sofifa.com/player/250995/mingjie-xiao/...,Mingjie Xiao,22,1997-01-01,177,66,China PR,Shanghai SIPG FC,48,...,44+2,43+2,43+2,43+2,44+2,46+2,47+2,47+2,47+2,46+2
Zhang Wei,252332,https://sofifa.com/player/252332/wei-zhang/20/...,张威,19,2000-05-16,186,75,China PR,Hebei China Fortune FC,48,...,47+2,49+2,49+2,49+2,47+2,47+2,49+2,49+2,49+2,47+2
Wang Haijian,251110,https://sofifa.com/player/251110/haijian-wang/...,汪海健,18,2000-08-02,185,74,China PR,Shanghai Greenland Shenhua FC,48,...,48+2,48+2,48+2,48+2,48+2,48+2,49+2,49+2,49+2,48+2
Pan Ximing,233449,https://sofifa.com/player/233449/ximing-pan/20...,潘喜明,26,1993-01-11,182,78,China PR,Hebei China Fortune FC,48,...,48+2,49+2,49+2,49+2,48+2,48+2,50+2,50+2,50+2,48+2

In [ ]:
# And here we can see that the new index is the 'short_name' column. And now we can easily
# identify each row

In [10]:
# selecting columns 
# we're going to select 7 out of 103 columns in the dataset. So here we're going to use the
# columns: long_name, age, dob, height_cm, weight_kg, nationality and club.

df = df[['long_name','age','dob','height_cm','weight_kg','nationality','club']]
df

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid
E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid
...,...,...,...,...,...,...,...
Shao Shuai,邵帅,22,1997-03-10,186,79,China PR,Beijing Renhe FC
Xiao Mingjie,Mingjie Xiao,22,1997-01-01,177,66,China PR,Shanghai SIPG FC
Zhang Wei,张威,19,2000-05-16,186,75,China PR,Hebei China Fortune FC
Wang Haijian,汪海健,18,2000-08-02,185,74,China PR,Shanghai Greenland Shenhua FC
Pan Ximing,潘喜明,26,1993-01-11,182,78,China PR,Hebei China Fortune FC

In [ ]:
# 'long_name' is the full name of the player, which is a string. Then we have the 'age' which is an integer. 
# Then 'dob' means date of birth, which is a date object. Then we have the height in cm, also an integer. 
# the weight, which is in kilograms (integer). We have the nacionality (string) and the club each player play
# by the year 2020.